spring.datasource.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/test?useSSL=false"
spring.datasource.username: "root"
spring.datasource.password: "password"
requestDate.format: "yyyy-MM-dd HH:mm:ss.SSS"
queryDate.format: "%Y-%d-%m.%T"
accesslog: "./access.log"
startDate: "2018-01-01.12:00:00"
duration: "hourly"
threshold: "200"